[variables]
MAVEN_OPTS = "-Xmx1024m"
SPRING_PROFILES_ACTIVE = "prod"

[phases.setup]
nixPkgs = ["openjdk17"]

[phases.build]
dependsOn = ["setup"]
cmds = [
  "cd obs",
  "chmod +x mvnw",
  "./mvnw clean package -DskipTests"
]

[start]
cmd = "cd obs && java -jar target/online-bookstore-0.0.1-SNAPSHOT.jar" 