[variables]
MAVEN_OPTS = "-Xmx1024m"
SPRING_PROFILES_ACTIVE = "prod"

[phases.setup]
nixPkgs = ["openjdk17"]

[phases.build]
dependsOn = ["setup"]
workDir = "/app/obs"
cmds = [
  "chmod +x mvnw",
  "./mvnw clean package -DskipTests"
]

[start]
workDir = "/app/obs"
cmd = "java -jar target/online-bookstore-0.0.1-SNAPSHOT.jar" 