version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: obs-mysql
    environment:
      MYSQL_ROOT_PASSWORD: Hellonghi@123
      MYSQL_DATABASE: obs_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - obs-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  app:
    build: .
    container_name: obs-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/obs_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Hellonghi@123
      BOOK_UPLOAD_DIR: /data/uploads/books
    ports:
      - "8080:8080"
    volumes:
      - book_images:/data/uploads/books
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - obs-network

volumes:
  mysql_data:
  book_images:

networks:
  obs-network:
    driver: bridge 